CREATE TABLE "user_account" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "username" varchar UNIQUE NOT NULL,
    "email" varchar UNIQUE NOT NULL,
    "password_hash" varchar NOT NULL,
    "salt" varchar,
    "is_active" boolean DEFAULT true,
    "is_banned" boolean DEFAULT false,
    "failed_login_attempts" integer DEFAULT 0,
    "last_failed_login" timestamp,
    "locked_until" timestamp,
    "last_login_at" timestamp,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now()),
    "password_changed_at" timestamp,
    "mfa_enabled" boolean DEFAULT false,
    "mfa_secret" varchar
);

CREATE TABLE "customer" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer UNIQUE NOT NULL,
    "first_name" varchar,
    "last_name" varchar,
    "phone_number" varchar,
    "date_of_birth" date,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "employee" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer UNIQUE NOT NULL,
    "employee_code" varchar UNIQUE,
    "first_name" varchar,
    "last_name" varchar,
    "department" varchar,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "role" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar UNIQUE NOT NULL,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "permission" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar UNIQUE NOT NULL,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now())
);

CREATE TABLE "user_role" (
    "user_id" integer,
    "role_id" integer,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now()),
    PRIMARY KEY ("user_id", "role_id")
);

CREATE TABLE "role_permission" (
    "role_id" integer,
    "permission_id" integer,
    "created_at" timestamp DEFAULT (now()),
    "updated_at" timestamp DEFAULT (now()),
    PRIMARY KEY ("role_id", "permission_id")
);

CREATE TABLE "audit_log" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer,
    "ip_address" varchar,
    "action_type" varchar NOT NULL,
    "target_entity" varchar,
    "target_id" varchar,
    "old_value" jsonb,
    "new_value" jsonb,
    "timestamp" timestamp DEFAULT (now())
);

CREATE TABLE "user_key" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" integer NOT NULL,
    "key_type" varchar NOT NULL,
    "key_value" varchar NOT NULL,
    "is_active" boolean DEFAULT true,
    "created_at" timestamp DEFAULT (now()),
    "expires_at" timestamp,
    "replaced_by" integer
);

ALTER TABLE "user_key"
    ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id");

ALTER TABLE "user_key"
    ADD FOREIGN KEY ("replaced_by") REFERENCES "user_key" ("id");

ALTER TABLE "audit_log"
    ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id");

ALTER TABLE "customer"
    ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id");

ALTER TABLE "employee"
    ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id");

ALTER TABLE "user_role"
    ADD FOREIGN KEY ("user_id") REFERENCES "user_account" ("id");

ALTER TABLE "user_role"
    ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "role_permission"
    ADD FOREIGN KEY ("role_id") REFERENCES "role" ("id");

ALTER TABLE "role_permission"
    ADD FOREIGN KEY ("permission_id") REFERENCES "permission" ("id");
